// <auto-generated />
using System;
using Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220114232318_tasklistkeys")]
    partial class tasklistkeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Common.Models.Task", b =>
                {
                    b.Property<int?>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TaskId"), 1L, 1);

                    b.Property<int>("AuthorUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("StatusTaskStatusID")
                        .HasColumnType("int");

                    b.Property<int>("TaskListID")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AuthorUserID");

                    b.HasIndex("StatusTaskStatusID");

                    b.HasIndex("TaskListID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Common.Models.Tasklist", b =>
                {
                    b.Property<int?>("TaskListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TaskListID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("OwnerUserID")
                        .HasColumnType("int");

                    b.HasKey("TaskListID");

                    b.HasIndex("OwnerUserID");

                    b.ToTable("TaskList");
                });

            modelBuilder.Entity("Common.Models.TaskStatus", b =>
                {
                    b.Property<int?>("TaskStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TaskStatusID"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TaskListID")
                        .HasColumnType("int");

                    b.HasKey("TaskStatusID");

                    b.HasIndex("TaskListID");

                    b.ToTable("TaskStatus");
                });

            modelBuilder.Entity("Common.Models.Ticket", b =>
                {
                    b.Property<int?>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TicketId"), 1L, 1);

                    b.Property<int>("AuthorUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("LastChangedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("AuthorUserID");

                    b.HasIndex("LastChangedByUserID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.Property<int?>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TasklistUser", b =>
                {
                    b.Property<int>("MembersUserID")
                        .HasColumnType("int");

                    b.Property<int>("TasklistsMemberedTaskListID")
                        .HasColumnType("int");

                    b.HasKey("MembersUserID", "TasklistsMemberedTaskListID");

                    b.HasIndex("TasklistsMemberedTaskListID");

                    b.ToTable("TasklistUser");
                });

            modelBuilder.Entity("Common.Models.Task", b =>
                {
                    b.HasOne("Common.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.TaskStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusTaskStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.Tasklist", "Tasklist")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Status");

                    b.Navigation("Tasklist");
                });

            modelBuilder.Entity("Common.Models.Tasklist", b =>
                {
                    b.HasOne("Common.Models.User", "Owner")
                        .WithMany("TasklistsOwned")
                        .HasForeignKey("OwnerUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Common.Models.TaskStatus", b =>
                {
                    b.HasOne("Common.Models.Tasklist", "Tasklist")
                        .WithMany("TaskStatuses")
                        .HasForeignKey("TaskListID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tasklist");
                });

            modelBuilder.Entity("Common.Models.Ticket", b =>
                {
                    b.HasOne("Common.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.User", "LastChangedBy")
                        .WithMany()
                        .HasForeignKey("LastChangedByUserID");

                    b.Navigation("Author");

                    b.Navigation("LastChangedBy");
                });

            modelBuilder.Entity("TasklistUser", b =>
                {
                    b.HasOne("Common.Models.User", null)
                        .WithMany()
                        .HasForeignKey("MembersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.Tasklist", null)
                        .WithMany()
                        .HasForeignKey("TasklistsMemberedTaskListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Models.Tasklist", b =>
                {
                    b.Navigation("TaskStatuses");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.Navigation("TasklistsOwned");
                });
#pragma warning restore 612, 618
        }
    }
}
