// <auto-generated />
using System;
using Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220104171155_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Common.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"), 1L, 1);

                    b.Property<int>("AuthorUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("StatusTaskStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("TaskListID")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AuthorUserID");

                    b.HasIndex("StatusTaskStatusID");

                    b.HasIndex("TaskListID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Common.Models.Tasklist", b =>
                {
                    b.Property<int>("TaskListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskListID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("OwnerUserID")
                        .HasColumnType("int");

                    b.HasKey("TaskListID");

                    b.HasIndex("OwnerUserID");

                    b.ToTable("TaskList");
                });

            modelBuilder.Entity("Common.Models.TaskStatus", b =>
                {
                    b.Property<int>("TaskStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskStatusID"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("TaskListID")
                        .HasColumnType("int");

                    b.HasKey("TaskStatusID");

                    b.HasIndex("TaskListID");

                    b.ToTable("TaskStatus");
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.Property<int?>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("TaskListID")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserID");

                    b.HasIndex("TaskListID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Common.Models.Task", b =>
                {
                    b.HasOne("Common.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.TaskStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusTaskStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.Tasklist", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListID");

                    b.Navigation("Author");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Common.Models.Tasklist", b =>
                {
                    b.HasOne("Common.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserID");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Common.Models.TaskStatus", b =>
                {
                    b.HasOne("Common.Models.Tasklist", null)
                        .WithMany("TaskStatuses")
                        .HasForeignKey("TaskListID");
                });

            modelBuilder.Entity("Common.Models.User", b =>
                {
                    b.HasOne("Common.Models.Tasklist", null)
                        .WithMany("Members")
                        .HasForeignKey("TaskListID");
                });

            modelBuilder.Entity("Common.Models.Tasklist", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("TaskStatuses");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
